export const errorMessages = {
  SE0: "Address cannot be Zero.",
  SE1: "Staking begin time must be greater than zero.",
  SE2: "Staking finish time must be greater than zero.",
  SE3: "The maximum stake must be greater than zero.",
  SE4: "The amount to be given per second must be greater than zero.",
  SE5: "Staking Off!",
  SE6: "Stakes must be greater than zero.",
  SE7: "The minimum stake cannot be zero.",
  SE8: "The maximum stake cannot be zero.",
  SE9: "Staking has not started yet.",
  SE10: "Staking is end.",
  SE11: "You are exceeding the total stake pool size! Enter a lower stake amount.",
  SE12: "You have no Balance.",
  SE13: "You did not reach the minimum stake.",
  SE14: "You have exceeded the maximum stake.",
  SE15: "The user has exceeded the maximum bet amount.",
  SE16: "You have no confirmed balance.",
  SE17: "The new value must be different from the old value.",
  SE18: "Time change error.",
  SE19: "The value must be greater than zero.",
  SE20: "Value error.",
  SE21: "You are not Authorized.",
  SE22: "No balance allocated for Allowance.",
  SE23: "Insufficient tokens.",
  SE24: "Fee Rate should be a minimum of 0 and a maximum of 10.",
  SE25: "Value must be greater than 0 for Fee transfer.",
  SE26: "Amount cannot be zero.",
  PE0: "You Don't Own PIS.",
  PE1: "Owner already exists.",
  PE2: "Record already exists.",
  PE3: "SubRecord already exists.",
  PE4: "You are not the domain owner.",
  PE5: "The maximum number of Sub Domains cannot be exceeded.",
  PE6: "Record not found.",
  PE7: "Subdomain Not Found.",
  PE8: "Invalid Length.",
  PE9: "The new value must be different from the old value.",
  PE10: "SubDomain cannot be transferred.",
  PE11: "Sender record not found.",
  PE12: "Receiver record not found.",
  PE13: "You are not the domain owner.",
  PE14: "The maximum number of Sub Domains cannot be exceeded.",
  PE15: "No record found to transfer.",
  ME0: "Owners addresses required.",
  ME1: "Owners and Roles mismatch.",
  ME2: "Invalid owner.",
  ME3: "Owner not unique.",
  ME4: "You are not Owners.",
  ME5: "Signature does not exist.",
  ME6: "Signature already confirmed.",
  ME7: "Signature already executed.",
  ME8: "Owner address cannot be Zero.",
  ME9: "The new value must be different from the old value.",
  ME10: "Unauthorized Request.",
  ME11: "Not Authorized.",
  ME12: "The signature has not started yet.",
  ME13: "Signature timeout.",
  ME14: "Transaction failed.",
  ME15: "Transaction not confirmed.",
};
